### ISSUE TITLE
plugin usage for ide's suggested removal

### ISSUE THREAD

**Issue by hazendaz** [mybatis/parent#11]
maven-idea-plugin is retired and probably should be removed.
maven-eclipse-plugin is flagged for future retirement.  Using this with modern eclipse versions actually causes way more issues than it attempts to solve since it does a lot of legacy things and m2e is preferred these days.

For eclipse plugin being potentially retired...
http://maven.40175.n5.nabble.com/DISCUSS-Move-everything-to-1-6-take-2-was-Re-I-can-t-make-a-release-td5820796.html#a5820985

If no objections, I can do a pull request on this.  Thanks.

**Comment by nmaves** [comment]
Honestly I don't really see a reason to have this at all.   Any recent IDE can create a project from a pom.xml.  I say we just remove them both.

**Comment by emacarron** [comment]
+1

**Comment by hazendaz** [comment]
Removed and merged.
