### ISSUE TITLE
Invalid value passed to m-enforcer-p rule "requireJavaVersion"

### ISSUE THREAD

**Issue by kwin** [mybatis/parent#401]
Only version ranges according to https://maven.apache.org/enforcer/enforcer-rules/requireJavaVersion.html and https://maven.apache.org/enforcer/enforcer-rules/versionRanges.html are supported but currently just a comma separated list of major versions are passed in https://github.com/mybatis/parent/blob/fcf4376a917a2ccbe72b9dc6de0a6eb99f6c32c5/pom.xml#L612.

Although this works for requiring a lower bound (more or less by incident, for details refer to https://github.com/eclipse-m2e/m2e-core/issues/1120) it doesn't work for enforcing the upper bound properly. Also it won't accept version "11" but only a minor version above 0!
This value must either be a single version (for just requiring a minimum version) or a range starting with either `(` or `[`.

**Comment by hazendaz** [comment]
ok got PR adjusting the rule.  The prior just allowed anything >= 11.  New rule will enforce any 11, any 17, any 19, any 20 and nothing else.

**Comment by kwin** [comment]
It was a valid version constraint but not what you expected. Look at
