### ISSUE TITLE
Question:  what's the purpose of sonatype-oss-snapshots repository defined in POM?

### ISSUE THREAD

**Issue by WestFarmer** [mybatis/parent#425]

**Comment by hazendaz** [comment]
This parent is used for the whole of mybatis projects.  We publish every commit to the default branch (master) to sonatype snapshots so its available for testing to users well before any release happens.

**Comment by WestFarmer** [comment]
any chance to remove this in a release version ? you know this will cause unnecessary HTTP requests during maven building process. for example my projects  depend on some SNAPSHOTS dependency, when doing maven build it  always try to download  from sonatype-oss-snapshots, even I work in a environment without internet access.
this problem is not a big deal, but for perfection, I think it's not reasonable to keep a repository in released version, which was used for testing purpose only.
How do you think ? thanks.
@hazendaz

**Comment by hazendaz** [comment]
sounds to me you have other unrelated issues.  If you have http blocked and you are just trying to build mybatis, then you also cannot get to central which is still sonatype (basically same place).  Presumably you had to override central usage to build the project so you would do the same to snapshots.  Nothing that special about it.  It won't be removed though...
